// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjCr8nuDKvpvKUFKfOhb46b17E-EdT7VA',
    appId: '1:1080437047880:web:7ac59870dd5de2d9cb8e7d',
    messagingSenderId: '1080437047880',
    projectId: 'note-app-13b15',
    authDomain: 'note-app-13b15.firebaseapp.com',
    storageBucket: 'note-app-13b15.firebasestorage.app',
    measurementId: 'G-S2RMCZNXHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcKv8CNFV75tCRKEb5rXV9n3FoPs90T2M',
    appId: '1:1080437047880:android:a0ab32ec9df34c71cb8e7d',
    messagingSenderId: '1080437047880',
    projectId: 'note-app-13b15',
    storageBucket: 'note-app-13b15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAJSRY7jcy8NnWDwiHgrS1SRWgWeTJXfY',
    appId: '1:1080437047880:ios:98389239506abb9bcb8e7d',
    messagingSenderId: '1080437047880',
    projectId: 'note-app-13b15',
    storageBucket: 'note-app-13b15.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNoteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAJSRY7jcy8NnWDwiHgrS1SRWgWeTJXfY',
    appId: '1:1080437047880:ios:98389239506abb9bcb8e7d',
    messagingSenderId: '1080437047880',
    projectId: 'note-app-13b15',
    storageBucket: 'note-app-13b15.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNoteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjCr8nuDKvpvKUFKfOhb46b17E-EdT7VA',
    appId: '1:1080437047880:web:598fcd0e5406283ecb8e7d',
    messagingSenderId: '1080437047880',
    projectId: 'note-app-13b15',
    authDomain: 'note-app-13b15.firebaseapp.com',
    storageBucket: 'note-app-13b15.firebasestorage.app',
    measurementId: 'G-VNRXPFYV4M',
  );
}
